### ISSUE TITLE
splash screen

### ISSUE THREAD

**Issue by michael-lefebvre** [gitscout/desktop#1]
At app launch, there is a short moment where we don't know if user is logged in or not (see attachment). We need a pseudo "splash screen/generic background".
<img width="402" alt="capture d ecran 2015-12-03 a 22 27 08" src="https://cloud.githubusercontent.com/assets/279053/11574736/a64dd55c-9a0d-11e5-9d5e-1c149aa60018.png">

**Comment by jeremybenaim** [comment]
@michael-lefebvre what about a fake loader ? (force timeout)

**Comment by michael-lefebvre** [comment]
yep, it's all about design because we don't have any information about loading progression.

**Comment by jeremybenaim** [comment]
Zut! No promise?
