### ISSUE TITLE
reversed order for issue's comments

### ISSUE THREAD

**Issue by michael-lefebvre** [gitscout/desktop#2]
when we inverse comments order, the issue description who was originally displayed as the first comment must go to the list end. this looks strange 'cause this message provides major informations about the issue. And it doesn't makes sense to keep it on top (see screen shot). Any proposals ?

<img width="437" alt="capture d ecran 2015-12-08 a 21 05 25" src="https://cloud.githubusercontent.com/assets/279053/11666983/778502c8-9def-11e5-9e5b-b770ba355242.png">

**Comment by areskub** [comment]
Why do we need to reverse the order again? I can't remember

**Comment by adriengriveau** [comment]
We don't need that

**Comment by michael-lefebvre** [comment]
@areskub we thought about reverse order because in a long list of comment you need to scroll a lot to see the form. By reversing the order we can display the form on top of the list. But this introduce another problem. The first comment of the list is the description of the issue. So we lost the main informations about the issue.
Another solution might be to stick the form at the bottom of the view ?

**Comment by michael-lefebvre** [comment]
let's see later
