### ISSUE TITLE
Settings window content

### ISSUE THREAD

**Issue by michael-lefebvre** [gitscout/desktop#3]
to complete:

### App

* Launch app at (os) login
* Subscription 

### Display

* issue sort: What to sort results by. Can be either created, updated, comments + the direction of the sort. Default: created desc
* issue state: Indicates the state of the issues to return. Can be either _open_ or _all_.
* repositories sort : idem issues

**Comment by adriengriveau** [comment]
UI benchmark - state

![capture d ecran 2015-12-18 a 20 11 02](https://cloud.githubusercontent.com/assets/10723029/11910407/d14d12f6-a5c3-11e5-97d2-d0c5ea158f81.png)

**Comment by adriengriveau** [comment]
<img width="331" alt="capture_d_____cran_2015-12-19____02 25 26" src="https://cloud.githubusercontent.com/assets/10723029/11910513/37951c1e-a5c6-11e5-960b-d7310fd22c7b.png">
